export const dummyProducts = [
    {
        id: "1",
        title: "Wireless Mouse",
        description: "Ergonomic wireless mouse with adjustable DPI.",
        price: 799,
        stock: 120,
        category: "Electronics",
        image: "https://via.placeholder.com/150",
    },
    {
        id: "2",
        title: "Cotton T-Shirt",
        description: "100% pure cotton regular fit t-shirt for all-day comfort.",
        price: 499,
        stock: 85,
        category: "Clothing",
        image: "https://via.placeholder.com/150",
    },
    {
        id: "3",
        title: "Ceramic Coffee Mug",
        description: "Microwave-safe ceramic mug with matte finish.",
        price: 299,
        stock: 200,
        category: "Home & Kitchen",
        image: "https://via.placeholder.com/150",
    },
    {
        id: "4",
        title: "Bluetooth Speaker",
        description: "Compact speaker with deep bass and 12-hour battery.",
        price: 1499,
        stock: 40,
        category: "Electronics",
        image: "https://via.placeholder.com/150",
    },
    {
        id: "5",
        title: "Notebook (A5)",
        description: "Spiral-bound ruled notebook with 200 pages.",
        price: 129,
        stock: 500,
        category: "Stationery",
        image: "https://via.placeholder.com/150",
    },
    {
        id: "5",
        title: "Notebook (A5)",
        description: "Spiral-bound ruled notebook with 200 pages.",
        price: 129,
        stock: 500,
        category: "Stationery",
        image: "https://via.placeholder.com/150",
    },
    {
        id: "5",
        title: "Notebook (A5)",
        description: "Spiral-bound ruled notebook with 200 pages.",
        price: 129,
        stock: 500,
        category: "Stationery",
        image: "https://via.placeholder.com/150",
    },
    {
        id: "5",
        title: "Notebook (A5)",
        description: "Spiral-bound ruled notebook with 200 pages.",
        price: 129,
        stock: 500,
        category: "Stationery",
        image: "https://via.placeholder.com/150",
    },
]
